FROM apache/airflow:2.9.2-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    nano git curl wget && \
    rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.airflow.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

WORKDIR /opt/airflow
