FROM python:3.12-slim

WORKDIR /app

# install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt && pip install streamlit

COPY dashboard /app/

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
