FROM python:3.10-slim

WORKDIR /app

COPY requirements.etl.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src /app/src
COPY data /app/data
COPY raw_data /app/raw_data

CMD ["tail", "-f", "/dev/null"]
